sonar.projectKey=mauriciovelasquezduoc_202601_DOY0101-003D_sprintboot_gradle
sonar.organization=mauriciovelasquezduoc
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.source=21
sonar.java.target=21

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=.github/**,k8s/**,docs/**,**/test/**

sonar.sourceEncoding=UTF-8
